DROP TRIGGER IF EXISTS trigger_update_booking_personal_access_for_access ON access_personal;

DROP TRIGGER IF EXISTS trigger_update_booking_group_access_for_access ON access_group;

DROP TRIGGER IF EXISTS trigger_update_booking_coach_access_for_access ON access_coach;